name: Write__Adapt__
title: WriteAdapt - For People Who Love Content
org: Strategy Media
author: dhaub
author_url: https://github.com/dhaub
base_url: ''
ctx_path: ''
asciidoctor:
  :safe: safe
  :attributes:
    sitename: WriteAdapt
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font