name: Write__Adapt__
title: WriteAdapt - For People Who Love Content
org: Strategy Media
author: dhaub
author_url: https://github.com/dhaub
base_url: ''
ctx_path: ''
asciidoctor:
  :safe: safe
  :attributes:
    sitename: WriteAdapt
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font

profiles:
  development:
    deploy: nil 
  production:
    base_url: http://dhaub.github.io/writeadapt-dhaub
    ctx_path: /writeadapt-dhaub
    asciidoctor:
      :attributes:
        base_url: http://dhaub.github.io/writeadapt-dhaub
        ctx_path: /writeadapt-dhaub
        imagesdir: http://dhaub.github.io/writeadapt-dhaub/images 
    deploy:
      host: github_pages
      branch: gh-pages